#!/bin/bash

assertPass(){
    $@
    assertEquals '$@ failed' 0 $?
}

assertPassInt(){
    $@ &
    pid=$!;
    sleep 5
    kill -0 $pid
    assertEquals '$@ exited early' 0 $?
    kill -INT $pid
    assertEquals '$@ failed' 0 $?
    wait $pid
    assertEquals '$@ returned $?' 0 $?
}

assertPassTerm(){
    $@ &
    pid=$!;
    sleep 5
    kill -0 $pid
    assertEquals '$@ exited early' 0 $?
    kill -TERM $pid
    assertEquals '$@ failed' 0 $?
}

# assertFileContains
# Param1: Filename
# Param2: pattern
assertFileContains(){
    egrep $2 $1 | grep -v 'grep' &>/dev/null
    assertEquals 'Missing content in file' 0 $?
}
assertFileNotContains(){
    egrep $2 $1 | grep -v 'grep' &>/dev/null
    assertEquals 'File should not contain the keyword' 1 $?
}


. $(dirname $0)/../lib/shunit2
